### PR TITLE
In 162 update test directory parser to handle incoming test directory

### PR DESCRIPTION
**Pull request by Yu-jinKim**
Big changes:
- Addition of new config json for the April 2023 (v5) rare disease test directory (TD)
- Checking mode for updating test directory in panel database. Useful for sense checking the TD data

Smol change:
- Capture the change column from the test directory in the json

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

___
*[`main.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRJ9nyoEv8uRnBs4Qh-:-NRJ9nyoEv8uRnBs4Qh0:batzj0z) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/main.py#L36)):*
> ```Python
>         print("Parsing of the cancer test directory is not implemented yet")
> 
>     elif cmd == "checker":
> ```

what is `checker`?



_Code quote:_
```Python
 elif cmd == "checker":
```
___
*[`test_directory_parser/output_checker.py` line 26 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRJD9Gy0pa9XR5xlu2x:-NRJD9Gy0pa9XR5xlu2y:bpdf2bd) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/output_checker.py#L26)):*
> ```Python
>     # since we have add on version we need to get all versions that contain
>     # the previously gathered max version
>     # i.e. ["2.0", "2.1", "2.1|1"] --> ["2.1", "2.1|1"]
> ```

what are the pipes doing here?



_Code quote:_
```Python
"2.1|1"]
```
___
*[`test_directory_parser/output_checker.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRJCypG2yD0vNvv_DYL:-NRJCypG2yD0vNvv_DYM:bv6vm3g) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/output_checker.py#L41)):*
> ```Python
>     else:
>         # if we have multiple elements in the list, that probably means that
>         # we have at least one add on version in the list.
> ```

what do you mean by add on version?



_Code quote:_
```Python
add on version
```
___
*[`test_directory_parser/output_checker.py` line 57 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRJCnq3EKIUuXz15nn1:-NRJCnq3EKIUuXz15nn2:b-l3k5jv) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/output_checker.py#L57)):*
fyi the `str()` is not needed in f strings:
```
>>> a = Version('1.0.1')
>>> a
<Version('1.0.1')>
>>> f"{a}"
'1.0.1'
```



_Code quote:_
```Python
str
```
___
*[`test_directory_parser/output_checker.py` line 109 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRXCjcQ4hueQXmMJdX-:-NRXCjcQ4hueQXmMJdX0:b8l0fcc) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/output_checker.py#L109)):*
> ```Python
> 
>     else:
>         return
> ```

what is happening here and how is it handled?
___
*[`test_directory_parser/rare_disease.py` line 50 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRXDaYT8MyDNmbNrAh_:-NRXDaYT8MyDNmbNrAha:b-wpeuhc) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/rare_disease.py#L50)):*
> ```Python
>                 else:
>                     raise Exception((
>                         "2 or more columns were detected as having 'Changes' "
> ```

can you add what is found to the exception raised to know what its matched



_Code quote:_
```Python
                        "2 or more columns were detected as having 'Changes' "
                        "in their name breaking the changes gathering."
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRJ9nyoEv8uRnBs4Qh-:-NRXEECXCVJPscaQC5H7:b-fakbin) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/main.py#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is `checker`?
</blockquote></details>

checker is the subparser i.e. the cmd name that unlocks the some subcommands
___
*[`test_directory_parser/output_checker.py` line 26 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRJD9Gy0pa9XR5xlu2x:-NRXEPQz5a_w97pMY3q-:bqwa35x) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/output_checker.py#L26)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what are the pipes doing here?
</blockquote></details>

add on panels are panelapp panels which had their content modified by the lab to bypass the slow panelapp update process
___
*[`test_directory_parser/output_checker.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRJCypG2yD0vNvv_DYL:-NRXEb04BJAcjWyu1ZLb:b-iknxln) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/output_checker.py#L41)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what do you mean by add on version?
</blockquote></details>

add on panels are panelapp panels which had their content modified by the lab to bypass the slow panelapp update process
___
*[`test_directory_parser/output_checker.py` line 57 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRJCnq3EKIUuXz15nn1:-NRXEdEu7gGYc9Q69Sfc:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/output_checker.py#L57)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

fyi the `str()` is not needed in f strings:
```
>>> a = Version('1.0.1')
>>> a
<Version('1.0.1')>
>>> f"{a}"
'1.0.1'
```
</blockquote></details>

Done.
___
*[`test_directory_parser/output_checker.py` line 109 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRXCjcQ4hueQXmMJdX-:-NRXF2RcEj40-vOoo7Lr:b-cwvtnl) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/output_checker.py#L109)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is happening here and how is it handled?
</blockquote></details>

if we couldn't find the panelapp id in the database, we return None. That will be caught in the function that calls `get_current_panel_genes` and it will print that the genes for that panelapp id couldn't be found and it will skip to the next iteration of the for loop
___
*[`test_directory_parser/rare_disease.py` line 50 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRXDaYT8MyDNmbNrAh_:-NRXFfDk9yL37jqOhV0j:b-bb1ftx) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/rare_disease.py#L50)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add what is found to the exception raised to know what its matched
</blockquote></details>

it's a preventive exception. If 2 or more columns contain the word Changes, i raise the exception

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

___
*[`test_directory_parser/rare_disease.py` line 50 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRXDaYT8MyDNmbNrAh_:-NRXRLEH-BtDArYdq0kV:b-ll84mi) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/rare_disease.py#L50)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

it's a preventive exception. If 2 or more columns contain the word Changes, i raise the exception
</blockquote></details>

as in can you add `change_column` to the message so you know what its matched, or is that not useful?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`test_directory_parser/rare_disease.py` line 50 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6#-NRXDaYT8MyDNmbNrAh_:-NRXWFytE4k6qVYL3JCk:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/ba5875d7216cb9f8c58bd42f5a0d998a2d64e825/test_directory_parser/rare_disease.py#L50)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as in can you add `change_column` to the message so you know what its matched, or is that not useful?
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 10 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
