### PR TITLE
Update test directory parser for test directory v6

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- New test directory config to integrate a new test method for CNV tests
- New bit of code to filter clinical indications using an internal test directory

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20)

### CODE REVIEW

**Review by corbin-chris — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20)* status: all files reviewed, 4 unresolved discussions (waiting on @Yu-jinKim)

___
*[`README.md` line 2 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20#-Ni-uPBrE4XbR6drfFYT:-Ni-uPBs2JQnQgNatQCn:b-8dip8m) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/14245efd9d2c03094b2bc5c275805df4cf3e545b/README.md#L2)):*
> ```Markdown
> # test_directory_parser
> Script(s) to parse the test directories
> ```

Add here that you're parsing the test directories to feed them into the panel database (or sanity-check them, or whatever you're planning for them)
___
*[`README.md` line 33 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20#-Ni-uvAP5N04J1Y1z4Pn:-Ni-uvAP5N04J1Y1z4Po:b65gws3) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/14245efd9d2c03094b2bc5c275805df4cf3e545b/README.md#L33)):*
> ```Markdown
> ### Config file
> 
> The config file is used to indicated the header line, the name of the sheet of interest and the name of the columns that need to be gathered and processed.
> ```

Typo: indicated should be indicate 
___
*[`README.md` line 102 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20#-Ni-uFt71GZdWRso4DdE:-Ni-uFt71GZdWRso4DdF:b2645cz) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/14245efd9d2c03094b2bc5c275805df4cf3e545b/README.md#L102)):*
> ```Markdown
>       .
>     }
> }
> ```

Could you add a sentence or two about how this JSON gets used later?
___
*[`test_directory_parser/test_directory.py` line 35 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20#-Ni-woc9BlkbC5qvKnPK:-Ni-woc9BlkbC5qvKnPL:bc454bo) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/14245efd9d2c03094b2bc5c275805df4cf3e545b/test_directory_parser/test_directory.py#L35)):*
> ```Python
>         self.data = sheet.to_dict()
>         self.td = Path(test_directory_path).name
>         self.type = td_type
> ```

'type' shouldn't be used as an identifier, as it is a Python reserved word (you don't want to shadow the built-in 'type()'). Could you please rename to 'type_td' or something like that instead?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @corbin-chris)

___
*[`README.md` line 2 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20#-Ni-uPBrE4XbR6drfFYT:-Ni0Ak483Bb7J_BPSbjp:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/14245efd9d2c03094b2bc5c275805df4cf3e545b/README.md#L2)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Add here that you're parsing the test directories to feed them into the panel database (or sanity-check them, or whatever you're planning for them)
</blockquote></details>

Done.
___
*[`README.md` line 102 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20#-Ni-uFt71GZdWRso4DdE:-Ni0D4820QB_uYEu3emB:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/14245efd9d2c03094b2bc5c275805df4cf3e545b/README.md#L102)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you add a sentence or two about how this JSON gets used later?
</blockquote></details>

Done.
___
*[`test_directory_parser/test_directory.py` line 35 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20#-Ni-woc9BlkbC5qvKnPK:-Ni0DSUv-dTeToXvc8yb:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/14245efd9d2c03094b2bc5c275805df4cf3e545b/test_directory_parser/test_directory.py#L35)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

'type' shouldn't be used as an identifier, as it is a Python reserved word (you don't want to shadow the built-in 'type()'). Could you please rename to 'type_td' or something like that instead?
</blockquote></details>

Done.

**Review by corbin-chris — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20)* status: all files reviewed, 1 unresolved discussion (waiting on @Yu-jinKim)

**Review by corbin-chris — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
