### PR TITLE
In 471 test directory parser v1.4.0

### LINKED ISSUE #21: Introduce unittesting
Nothing is unittested, probably needs to be

### LINKED ISSUE #22: Filter using the specialism
A lot of clinical indications are not used by the lab and can be filtered down using the specialism

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Resolves #21 
- Resolves #22 
- New config file to include specialism
- Removed SQLAlchemy from requirements
    - Remove unused function to connect to database

### Unittest

```
python -m unittest test_directory_parser.tests
............
----------------------------------------------------------------------
Ran 12 tests in 0.180s

OK
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24)* status: 7 of 13 files reviewed, 9 unresolved discussions (waiting on @Yu-jinKim)

___
*[`README.md` line 14 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruLKQS3nbqo3Ty6LzJ:-NruLKQTBvu5MQ8wNdqV:b-g2nk3c) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/README.md#L14)):*
> ```Markdown
> ```bash
> sudo apt-get install libmysqlclient-dev
> ```
> ```

is this still true?



_Code quote:_
```Markdown
### Linux packages

The following linux package needs to be installed for the `mysqlclient` Python package to be installed:

```bash
sudo apt-get install libmysqlclient-dev
```
```
___
*[`README.md` line 112 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruLC2A5dUMr206quoB:-NruLC2A5dUMr206quoC:b723pmv) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/README.md#L112)):*
> ```Markdown
>       .
>     }
> }
> ```

this be not valid JSON, should it be or is it just meant to indicate there's more?



_Code quote:_
```Markdown
    {
      .
      .
      .
    }
}
```
___
*[`requirements.txt` line 6 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruU-7IBWh3S8zyTYeA:-NruU-7J6e2pfhagV4sV:bqmnsq0) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/requirements.txt#L6)):*
> ```help
> greenlet==2.0.2
> idna==3.4
> mysqlclient==2.1.1
> ```

still needed? If you've changed lots you can regenerate an up to date req file with this: https://github.com/bndr/pipreqs 



_Code quote:_
```help
mysqlclient==2.1.1
```
___
*[`configs/240226_RD.json` line 3 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruJrbx5S609YsWguO2:-NruJrbx5S609YsWguO3:b-w2y8sx) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/configs/240226_RD.json#L3)):*
> ```JSON
> {
>     "name": "240226_RD",
>     "sheet_of_interest": "R&ID indications",
> ```

what is `R&ID`?



_Code quote:_
```JSON
R&ID
```
___
*[`test_directory_parser/utils.py` line 116 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruUMs8Bhg3-3tyZWfc:-NruUMs8Bhg3-3tyZWfd:b-5sm58z) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/utils.py#L116)):*
> ```Python
>             if len(df_previous_symbols) == 0 and len(df_alias_symbols) == 0:
>                 # couldn't find a previous or alias symbol
>                 return df_res
> ```

unit tests don't cover this



_Code quote:_
```Python
            if len(df_previous_symbols) == 0 and len(df_alias_symbols) == 0:
                # couldn't find a previous or alias symbol
                return df_res
```
___
*[`test_directory_parser/utils.py` line 141 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruUIuO2zP5cjSwLPGL:-NruUIuO2zP5cjSwLPGM:b-jqywnb) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/utils.py#L141)):*
> ```Python
>             elif len(df_alias_symbols) >= 1:
>                 df_res.at["Previous"] = False
>                 df_res.at["Alias"] = True
> ```

unit tests don't cover these conditionals



_Code quote:_
```Python
            elif len(df_previous_symbols) >= 1:
                df_res.at["Previous"] = True
                df_res.at["Alias"] = False

            elif len(df_alias_symbols) >= 1:
                df_res.at["Previous"] = False
                df_res.at["Alias"] = True
```
___
*[`test_directory_parser/tests/test_clinical_indication.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruV5B_5sMD-66e2hDz:-NruV5B_5sMD-66e2hE-:b-2ribhq) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/tests/test_clinical_indication.py#L3)):*
> ```Python
> import unittest
> from unittest.mock import patch
> ```

clinical_indication.py isn't in the PR so will add comments here, at like 28-31 you add _G and _P suffixes, are we still wanting to do this? If so, line 29 for _G isn't covered by tests

plus last line where you add None into your genes list isn't covered by a test
___
*[`test_directory_parser/tests/test_rare_disease.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruVTVm0Fcz6KmOj8ZC:-NruVTVm0Fcz6KmOj8ZD:bpk5u15) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/tests/test_rare_disease.py#L13)):*
> ```Python
> PATH_TO_TEST_FOLDER = Path(".") / "test_directory_parser" / "tests" / "test_data"
> 
> class TestRareDisease(unittest.TestCase):
> ```

Exceptions at lines 49 and 56 aren't covered by tests
___
*[`test_directory_parser/tests/test_test_directory.py` line 74 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruUftJ4Eh01zxJ3Ukv:-NruUftK3KAnmsG9FJmU:b-8fwdhv) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/tests/test_test_directory.py#L74)):*
> ```Python
> 
>         with self.subTest():
>             self.assertEqual(len(td.all_clinical_indications), 2)
> ```

no tests for `filter_clinical_indications()` and `output_json()`

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24)* status: 7 of 13 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 14 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruLKQS3nbqo3Ty6LzJ:-NrunqkX4tMYIPh3zFi5:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/README.md#L14)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this still true?
</blockquote></details>

Done.
___
*[`README.md` line 112 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruLC2A5dUMr206quoB:-NrunFkI21JV5esHrCAG:b-5n0hsa) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/README.md#L112)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this be not valid JSON, should it be or is it just meant to indicate there's more?
</blockquote></details>

yes, I have added examples instead
___
*[`requirements.txt` line 6 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruU-7IBWh3S8zyTYeA:-Nrup1Rp1kRqiafi3bCP:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/requirements.txt#L6)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

still needed? If you've changed lots you can regenerate an up to date req file with this: https://github.com/bndr/pipreqs
</blockquote></details>

Done.
___
*[`configs/240226_RD.json` line 3 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruJrbx5S609YsWguO2:-Nrup39j1N0sypyU9_E8:b-apf0x6) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/configs/240226_RD.json#L3)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is `R&ID`?
</blockquote></details>

I have absolutely no idea

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24)* status: 9 of 13 files reviewed, 5 unresolved discussions (waiting on @Yu-jinKim)

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24)* status: 9 of 13 files reviewed, 5 unresolved discussions (waiting on @jethror1)

___
*[`test_directory_parser/tests/test_test_directory.py` line 74 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruUftJ4Eh01zxJ3Ukv:-NsCvMBFD0XHPD3iQWmZ:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/tests/test_test_directory.py#L74)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

no tests for `filter_clinical_indications()` and `output_json()`
</blockquote></details>

Done.

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`test_directory_parser/tests/test_rare_disease.py` line 13 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruVTVm0Fcz6KmOj8ZC:-NsD0IFf9HkXouqLPS-8:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/tests/test_rare_disease.py#L13)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Exceptions at lines 49 and 56 aren't covered by tests
</blockquote></details>

Done.

**Comment by Yu-jinKim** [comment]
```
$ coverage run -m unittest -b test_directory_parser.tests
..................
----------------------------------------------------------------------
Ran 18 tests in 0.085s

OK

$ coverage report -m
Name                                                      Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------------------
test_directory_parser/__init__.py                             0      0   100%
test_directory_parser/clinical_indication.py                 29      0   100%
test_directory_parser/rare_disease.py                        20      0   100%
test_directory_parser/test_directory.py                      57      0   100%
test_directory_parser/tests/__init__.py                       4      0   100%
test_directory_parser/tests/test_clinical_indication.py      40      0   100%
test_directory_parser/tests/test_rare_disease.py             33      0   100%
test_directory_parser/tests/test_test_directory.py           48      0   100%
test_directory_parser/tests/test_utils.py                    32      0   100%
test_directory_parser/utils.py                               50      0   100%
---------------------------------------------------------------------------------------
TOTAL                                                       313      0   100%
```

**Review by Yu-jinKim — COMMENTED** [review]
Took longer than expected

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-:-NsDDeoc5dfzlHI6NC2k:be7e878)* status: 8 of 13 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`test_directory_parser/utils.py` line 116 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruUMs8Bhg3-3tyZWfc:-NsDDNcd3SXHoOWBjz22:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/utils.py#L116)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

unit tests don't cover this
</blockquote></details>

Done.
___
*[`test_directory_parser/utils.py` line 141 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruUIuO2zP5cjSwLPGL:-NsDDO7D4wacQHxTFzlL:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/utils.py#L141)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

unit tests don't cover these conditionals
</blockquote></details>

Done.
___
*[`test_directory_parser/tests/test_clinical_indication.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-NruV5B_5sMD-66e2hDz:-NsDDP4EB7SYQpD7mj_-:bsipkuf) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/c3d5e1078430f62e5abcf4395fd358383d5fb69b/test_directory_parser/tests/test_clinical_indication.py#L3)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

clinical_indication.py isn't in the PR so will add comments here, at like 28-31 you add _G and _P suffixes, are we still wanting to do this? If so, line 29 for _G isn't covered by tests

plus last line where you add None into your genes list isn't covered by a test
</blockquote></details>

I should have a talk about how eris handles the _G/P
Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24)* status: all files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24#-:-NsEOSF2Ax4xumDK6Q83:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/24)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
