### PR TITLE
transcript assigner

### LINKED ISSUE #8: Cmd in readme need update
```
# outputs a json containing cleaned data from the given test directory
python main.py --hgnc ${hgnc_dump.txt} rare_disease ${test_directory.xslx} configs/${config} [-o ${output_path}]
```
the command didn't work

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Functions to assign transcripts

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
think the readme could do with some more details adding since this PR adds new behaviour

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-:-NRhYrEgBZOCPzsHII2e:b-ykzs75)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @Yu-jinKim)

___
*[`main.py` line 87 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhYJZb9oP1IzlOW5oZ:-NRhYJZb9oP1IzlOW5o_:bt7s1ij) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/main.py#L87)):*
> ```Python
>             session, meta, mane_select_data, g2t_data
>         )
>         transcript_assigner.write_g2t(data, "g2t.tsv")
> ```

should this be named more uniquely? if we run it again and you have this file locally will it be overwritten?



_Code quote:_
```Python
g2t.tsv
```
___
*[`test_directory_parser/transcript_assigner.py` line 20 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVSAFBDibHUPa2qb-:-NRhVSAFBDibHUPa2qb0:b-pd7n0d) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L20)):*
> ```Python
>     with open(mane_file) as f:
>         for line in f:
>             # each column has quotes around them so i'm striping them
> ```

can you add an example line of the file here to make it easier to understand how its being parsed?



_Code quote:_
```Python
# each column has quotes around them so i'm striping them
```
___
*[`test_directory_parser/transcript_assigner.py` line 30 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVcCz2koZzBiyHA8g:-NRhVcCz2koZzBiyHA8h:bbxtuj3) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L30)):*
> ```Python
>                     mane_data[hgnc_id] = refseq
>                 else:
>                     print(f"Couldn't find hgnc id for {gene_symbol}")
> ```

is this missing id handled elsewhere?



_Code quote:_
```Python
print(f"Couldn't find hgnc id for {gene_symbol}")
```
___
*[`test_directory_parser/transcript_assigner.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhWGUW-qbbXdt9BRZ5:-NRhWGUW-qbbXdt9BRZ6:bwekmr7) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L36)):*
> ```Python
> 
> def parse_gene_transcript(g2t_file):
>     """ Parse gene to transcripts file (2 columns file)
> ```

hasn't g2t got 4 columns?



_Code quote:_
```Python
2 columns file
```
___
*[`test_directory_parser/transcript_assigner.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVlF42CuFAzfuSmIX:-NRhVlF42CuFAzfuSmIY:b-rmhstz) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L46)):*
> ```Python
> 
>     data = {}
> ```

should we add basic sense checks to these functions that they're reading the correct files?
___
*[`test_directory_parser/transcript_assigner.py` line 92 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhXD6tDxqpZOgeBlxG:-NRhXD6tDxqpZOgeBlxH:bxh8xnw) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L92)):*
> ```Python
>         raise Exception(
>             f"{hgnc_id} has the following transcripts in the HGMD database: "
>             f"{', '.join(hgmd_transcript)}"
> ```

can you add to this exception message why this is an error and how to fix
___
*[`test_directory_parser/transcript_assigner.py` line 135 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhXsmiAbR6aW5Mj7-0:-NRhXsmiAbR6aW5Mj7-1:b1ljhye) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L135)):*
> ```Python
>                 continue
> 
>             hgmd_transcript = find_HGMD_transcript(session, meta, gene)
> ```

do we get down here if there's no clinical transcript?
___
*[`test_directory_parser/transcript_assigner.py` line 141 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhY-BF3iIHMgxqhKjp:-NRhY-BF3iIHMgxqhKjq:bhgme7q) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L141)):*
> ```Python
> 
>                 if tx_base == hgmd_base:
>                     data[gene]["clinical_transcript"] = [tx, "HGMD"]
> ```

here you assign a clinical tx, but then it will drop to the below line of "no_clinical_transcript", is that intended?



_Code quote:_
```Python
data[gene]["clinical_transcript"] = [tx, "HGMD"]
```
___
*[`test_directory_parser/transcript_assigner.py` line 157 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhYSzs13RGg5fqfITa:-NRhYSzs13RGg5fqfITb:b-jctqad) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L157)):*
> ```Python
>     """
> 
>     with open(output_path, "w") as f:
> ```

this will overwrite any file with the matching name to `output_path`, is this intended?



_Code quote:_
```Python
w
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`test_directory_parser/transcript_assigner.py` line 20 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVSAFBDibHUPa2qb-:-NRh_ECg3jeOVmo_UcZi:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L20)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add an example line of the file here to make it easier to understand how its being parsed?
</blockquote></details>

Done.
___
*[`test_directory_parser/transcript_assigner.py` line 30 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVcCz2koZzBiyHA8g:-NRh_IbcE9NjeSwPHjzC:b-oogxf4) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L30)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this missing id handled elsewhere?
</blockquote></details>

i mean what can i do about it?
___
*[`test_directory_parser/transcript_assigner.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhWGUW-qbbXdt9BRZ5:-NRh_mUyA_Bj34wmZO0H:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

hasn't g2t got 4 columns?
</blockquote></details>

Done.
___
*[`test_directory_parser/transcript_assigner.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVlF42CuFAzfuSmIX:-NRhpyY53tYbpQymda4c:b-ysupk4) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L46)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should we add basic sense checks to these functions that they're reading the correct files?
</blockquote></details>

what kind?
formatting check?
___
*[`test_directory_parser/transcript_assigner.py` line 92 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhXD6tDxqpZOgeBlxG:-NRhaVaNC0jwRtuxv7Ik:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L92)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can you add to this exception message why this is an error and how to fix
</blockquote></details>

Done.
___
*[`test_directory_parser/transcript_assigner.py` line 135 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhXsmiAbR6aW5Mj7-0:-NRhaAbC8rWxCAbpEemT:b2nign6) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L135)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

do we get down here if there's no clinical transcript?
</blockquote></details>

yes
___
*[`test_directory_parser/transcript_assigner.py` line 141 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhY-BF3iIHMgxqhKjp:-NRhaGo533psytkztn4L:bok1p6t) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L141)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

here you assign a clinical tx, but then it will drop to the below line of "no_clinical_transcript", is that intended?
</blockquote></details>

Good catch. Fixed
___
*[`test_directory_parser/transcript_assigner.py` line 157 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhYSzs13RGg5fqfITa:-NRhaN3T1fpbt4ShKsRl:b-xgcult) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L157)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this will overwrite any file with the matching name to `output_path`, is this intended?
</blockquote></details>

i have a diabolical plan for this

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 87 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhYJZb9oP1IzlOW5oZ:-NRhsh26CWn61OsBvAA3:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/main.py#L87)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be named more uniquely? if we run it again and you have this file locally will it be overwritten?
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @Yu-jinKim)

___
*[`test_directory_parser/transcript_assigner.py` line 30 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVcCz2koZzBiyHA8g:-NRlZmI37GNqYRf87EdN:b-2ekhd4) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L30)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i mean what can i do about it?
</blockquote></details>

as in do we need to record this to make sure something isn't wrong / investigate these? will this mean they are missing if there's a typo or something?
___
*[`test_directory_parser/transcript_assigner.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhWGUW-qbbXdt9BRZ5:-NRlagdt9CW1gj7QGfsR:b-p9poot) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L36)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Done.
</blockquote></details>

is it?
___
*[`test_directory_parser/transcript_assigner.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVlF42CuFAzfuSmIX:-NRlahSwEc1lWBHVk8Ba:b-x4x2cy) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L46)):*
like that the file has correct no. columns, also why not use pandas for doing things like this as its much faster than reading through files line by line, if its just to turn 2 columns into a dict with the values being a list something like this works:

```
>>> df = pd.read_csv('test.tsv', names=['id', 'tx'], sep='\t')
>>> df
      id   tx
0  line1  foo
1  line2  bar

# turn it into a dict
>>> d = dict(zip(df['id'], df['tx']))
>>> d
{'line1': 'foo', 'line2': 'bar'}

# make values a list
>>> {k: [v] for k, v in d.items()}
{'line1': ['foo'], 'line2': ['bar']}
```
___
*[`test_directory_parser/transcript_assigner.py` line 157 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhYSzs13RGg5fqfITa:-NRlckc57GcLD_6l1DMG:b-dqfxc5) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L157)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i have a diabolical plan for this
</blockquote></details>

care to share?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`test_directory_parser/transcript_assigner.py` line 30 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVcCz2koZzBiyHA8g:-NRljEx0CTISHD6_uYfw:bx61hk2) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L30)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

as in do we need to record this to make sure something isn't wrong / investigate these? will this mean they are missing if there's a typo or something?
</blockquote></details>

i don't think so, it'll be a problem when trying to find a HGNC id in the gene/transcript file and we can't find a match in the MANE file
___
*[`test_directory_parser/transcript_assigner.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhWGUW-qbbXdt9BRZ5:-NRljhwa7SGLIdLY3tcq:bb5w40g) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is it?
</blockquote></details>

it's not the g2t file that we have in DNAnexus. It's a file created manually with genes and their transcripts in a 2 columns format. Don't know how to explain it better
___
*[`test_directory_parser/transcript_assigner.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVlF42CuFAzfuSmIX:-NRlpJIHDcqnvaT83tdL:b75hs85) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L46)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

like that the file has correct no. columns, also why not use pandas for doing things like this as its much faster than reading through files line by line, if its just to turn 2 columns into a dict with the values being a list something like this works:

```
>>> df = pd.read_csv('test.tsv', names=['id', 'tx'], sep='\t')
>>> df
      id   tx
0  line1  foo
1  line2  bar

# turn it into a dict
>>> d = dict(zip(df['id'], df['tx']))
>>> d
{'line1': 'foo', 'line2': 'bar'}

# make values a list
>>> {k: [v] for k, v in d.items()}
{'line1': ['foo'], 'line2': ['bar']}
```


</blockquote></details>

couldn't find how to make it work knowing that a key can be present multiple times in the id column.
I didn't like the chatgpt answer either. So i'm not changing it
___
*[`test_directory_parser/transcript_assigner.py` line 157 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhYSzs13RGg5fqfITa:-NRliiJA84vRiz1pkhpL:b-qad25l) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L157)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

care to share?
</blockquote></details>

i didn't write that where i wanted it.
Yeah, i think overwriting the file is fine

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`test_directory_parser/transcript_assigner.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhWGUW-qbbXdt9BRZ5:-NRqoOLr5irZfo_Rb17b:b1ujbot) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L36)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

it's not the g2t file that we have in DNAnexus. It's a file created manually with genes and their transcripts in a 2 columns format. Don't know how to explain it better
</blockquote></details>

is that file documented somewhere on how /why it was made and where it is? otherwise this code without your brain doesn't make sense (unless its in the readme already)
___
*[`test_directory_parser/transcript_assigner.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVlF42CuFAzfuSmIX:-NRqnYF21rHnVMQXgXNM:bn3eqmu) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L46)):*
some pandas fun can do exactly that with groupby:
```
>>> df = pd.read_csv('test.tsv', names=['id', 'tx'], sep='\t')
>>> df
      id   tx
0  line1  foo
1  line2  bar
2  line2  baz
>>> df.groupby('id').tx.apply(list).to_dict()
{'line1': ['foo'], 'line2': ['bar', 'baz']}
```

`groupby()` specified on the id column makes a series mapping the unique values in id, then calling `apply()` on the tx column makes that column a list, then `to_dict()` just turns those 2 columns to a normal dict

but also you can just leave it if you want

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`test_directory_parser/transcript_assigner.py` line 36 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhWGUW-qbbXdt9BRZ5:-NRrz52iEi1vj8a5S7S8:bpjgleo) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L36)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is that file documented somewhere on how /why it was made and where it is? otherwise this code without your brain doesn't make sense (unless its in the readme already)
</blockquote></details>

I have this, let me know if that's enough https://github.com/eastgenomics/test_directory_parser/tree/IN-162-Update-test-directory-parser-to-handle-incoming-test-directory#input-genestranscripts-file-for-transcript-assigner 
___
*[`test_directory_parser/transcript_assigner.py` line 46 at r1](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7#-NRhVlF42CuFAzfuSmIX:-NRrz2NICqML0zkBZBk6:b-896fix) ([raw file](https://github.com/eastgenomics/test_directory_parser/blob/e2efc72901e2eb6ed3c748f0ac9b35f845e9f774/test_directory_parser/transcript_assigner.py#L46)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

some pandas fun can do exactly that with groupby:
```
>>> df = pd.read_csv('test.tsv', names=['id', 'tx'], sep='\t')
>>> df
      id   tx
0  line1  foo
1  line2  bar
2  line2  baz
>>> df.groupby('id').tx.apply(list).to_dict()
{'line1': ['foo'], 'line2': ['bar', 'baz']}
```

`groupby()` specified on the id column makes a series mapping the unique values in id, then calling `apply()` on the tx column makes that column a list, then `to_dict()` just turns those 2 columns to a normal dict

but also you can just leave it if you want
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/test_directory_parser/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
